name: RDP

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    steps:
      - name: Download cloudflared
        run: |
          Invoke-WebRequest -Uri https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe

      - name: Enable and start RDP
        run: |
          Set-Service -Name TermService -StartupType Automatic
          Start-Service -Name TermService
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Set random password
        id: userinfo
        run: |
          $username = $env:USERNAME
          $password = [System.Web.Security.Membership]::GeneratePassword(32,3)
          net user $username $password
          Write-Output "::set-output name=username::$username"
          Write-Output "::set-output name=password::$password"

      - name: Start cloudflared tunnel (anonymous)
        run: |
          Start-Process -NoNewWindow -FilePath .\cloudflared.exe -ArgumentList "tunnel --url rdp://localhost:3389"
          Start-Sleep -Seconds 10

      - name: Show credentials
        run: |
          Write-Host "RDP Username: ${{ steps.userinfo.outputs.username }}"
          Write-Host "RDP Password: ${{ steps.userinfo.outputs.password }}"
          Write-Host "Check the previous step's logs for the .trycloudflare.com URL."
